data:
  AzureWebJobsStorage: ''
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: functionappcontagem
  namespace: ingress-nginx
---
data:
  host.master: V29KSnh1cXZBcFBFSE9rc0MwOThPN1EwWWpMQmJDOHJsTFNlNXFSODkzWWh3QllybDBXOXhRPT0=
  host.function.default: aXgxY1REaVovaHJ2UEFGTDBjeVFXSkhUTDh6QmtCR0ZjSE9CM2xLYWhralJMZlM4TUhWSmJnPT0=
  host.systemKey.default: NmpybGFubjZFcUdOTnZpRndaeHdMWVBVRkMwbUhDVWdTWk82M1hGczBNbzFLSUx2MlRPdzRBPT0=
  functions.valoratual.default: VGdHdkl5UmFYSEl0eER2YUs0MXBVcEdDNldTZlhNcFNWazhhNnY4TGh3RW84L2F5NWdHNWF3PT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-functionappcontagem
  namespace: ingress-nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: functionappcontagem-function-keys-identity-svc-act
  namespace: ingress-nginx
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: ingress-nginx
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: functionappcontagem-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: functionappcontagem-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: functionappcontagem-http
  namespace: ingress-nginx
spec:
  selector:
    app: functionappcontagem-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: functionappcontagem-http
  namespace: ingress-nginx
  labels:
    app: functionappcontagem-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: functionappcontagem-http
  template:
    metadata:
      labels:
        app: functionappcontagem-http
    spec:
      containers:
      - name: functionappcontagem-http
        image: renatogroffe/functionappcontagem:0
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: ValorAtual
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-functionappcontagem
        envFrom:
        - secretRef:
            name: functionappcontagem
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: functionappcontagem-function-keys-identity-svc-act
---

